### ISSUE TITLE
feature: Добавить разделить в логи

### ISSUE THREAD

**Issue by Kolesnikov-Vladislav** [EndoTouma/ADBController#1]
Раздел: Control

Поле: Output

Добавить разделитель между сообщениями, в случае когда пользователь отдаёт команду для выполнения.

Для чего? Будет удобнее понимать какая команда выполнена последней, а так же порядок команд.

В разделитель предлагаю добавить текст во всю ширину полю, с текстом: NEW COMMAND: DATE/TIME

Где DATE/TIME - это дата и время когда пользователь нажал на кнопку **Execute**

![image](https://github.com/EndoTouma/ADBController/assets/116725213/44ac1525-3ba7-40db-b6e2-46d50175efb7)

Прикладываю скрин, где красным выделена первая посланная команда, а синим вторая посланная команда

**Comment by EndoTouma** [comment]
Решено в https://github.com/EndoTouma/ADBController/commit/14dc2842af64cec942ba32bcf271090b396f720e
