### ISSUE TITLE
feature: Добавить сортировку по умолчанию от большего к меньшему IP

### ISSUE THREAD

**Issue by Kolesnikov-Vladislav** [EndoTouma/ADBController#2]
Раздел: Control

Добавить сортировку по умолчанию от меньшего к большему, сортировать по IP адресу. 

Правило: Новые устройства добавленные в список сразу попадают под правила сортировки. 

![image](https://github.com/EndoTouma/ADBController/assets/116725213/3ed84857-8f06-4049-a911-66d2034e4158)

**Comment by EndoTouma** [comment]
решено в https://github.com/EndoTouma/ADBController/commit/877d65cf7b3ff63a431229a4659eb7172c733ca0

**Comment by EndoTouma** [comment]
Добавил сортировку по возрастанию IP адреса
При добавлении нового устройство оно так же попадает под новые правила сортировки

https://github.com/EndoTouma/ADBController/commit/931a102d9f1cc735fdb4e6b60f8e214ea449bdfe
